apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-cls
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-cls
subjects:
  - kind: ServiceAccount
    name: fluent-bit-cls
    namespace: liteboxd-system
