apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: liteboxd-system
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - rbac-cluster.yaml
  - traefik-middleware-retry.yaml
  - pvc.yaml
  - api-service.yaml
  - api-deployment.yaml
  - api-pdb.yaml
  - gateway-service.yaml
  - gateway-deployment.yaml
  - gateway-pdb.yaml
  - ingress.yaml
