apiVersion: v1
kind: Service
metadata:
  name: liteboxd-web
  namespace: liteboxd-system
spec:
  selector:
    app: liteboxd-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
