apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: liteboxd-sandbox
resources:
  - namespace.yaml
  - rbac-api.yaml
  - rbac-gateway.yaml
  - networkpolicy-default-deny-all.yaml
  - networkpolicy-allow-dns.yaml
  - networkpolicy-deny-k8s-api.yaml
  - networkpolicy-allow-gateway-ingress.yaml
  - networkpolicy-allow-internet-egress.yaml
